### ISSUE TITLE
Error: Expression has changed after it was checked.

### ISSUE THREAD

**Issue by januff** [Kaizeras/ngx-redux-ui-management-recipes#1]
*Error: Expression has changed after it was checked. Previous value: 'CD_INIT_VALUE'. Current value: 'modal fade show'. It seems like the view has been created after its parent and its children have been dirty checked. Has it been created in a change detection hook ?*

Everything's looking good for me except the handleOpenModal method, which perhaps requires a different lifecycle-hook init? 

Really appreciate this guide, Hristo!

**Comment by januff** [comment]
My package.json was looking for "1.0.0-alpha.24" instead of the "1.0.0-alpha.20" version you specified. Correcting that solved my modal problem.

This is an amazing demo to study with redux-devtools-extension, btw. 

Great job in general, crazy-enlightening!

**Comment by Kaizeras** [comment]
Hey januff. I'll update the project's dependencies this weekend and I'll try to reproduce your problem.

I'm glad you found the guide useful!
