### ISSUE TITLE
state is undefined in layout.reducer.ts for getters

### ISSUE THREAD

**Issue by StevenFewster** [Kaizeras/ngx-redux-ui-management-recipes#3]
A couple of comments on this the disqus to the pluralSight article too

`export const getOpenedModalName = (state: State) => state.openedModalName;`

in all instances "Cannot read property 'openedModalName' of undefined"

when called from `this.openedModalName$ = store.select(fromRoot.getLayoutOpenedModalName);` and subscribed to with async.

**Comment by StevenFewster** [comment]
Fixable.

With your project set up as per the tutorial, and with your app.module.ts file containing
`StoreModule.forRoot({ reducer: metaReducer }),`

alter the index.ts file to have the following AppStore definition:
```
export interface AppState {
    reducer: {
        layout: fromLayout.State;
    };
}
```
and the getLayoutState function to be 
`export const getLayoutState = (state: AppState) => state.reducer.layout;`

**Comment by Kaizeras** [comment]
Thanks for pointing out @StevenFewster . I just fixed it in the tutorial. I will probably lock the package versions here in order to avoid inconsistencies.

Closing the issue.
